name: StarCraftStats
version: 1.0
main: fr.midey.starcraft.Stats
author: Midey
commands:
  set:
    description: modifie les stats d'un joueur
    permission: god.use
  stats:
    description: affiche les stats et grades du joueur
    permission: player.use
  wand:
    description: donne un wand au joueur
    permission: god.uses
  infos:
    description: affiche les informations du joueur
    permission: player.use